# Site configuration
domain: "http://songroger.win"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lshxin.com" # the base hostname & protocol for your site
permalink: /:title/
avatar: http://ouo0w16s7.bkt.clouddn.com/IMG_0754.JPG?e=1505118402&token=tYezop22TZHJ2SRLGu2c2pc_DIsOrZZ3JfZjeV5-:c2MkMIWAfzw5pPmwPci1MjBW0u4
about: http://7xof48.com1.z0.glb.clouddn.com/about.jpg
favicon: _src/images/favicon.png
basecss:
# Theme specific configuration
title: 小池的博客
description: >
  Hi there, My name is Luozhan.Song, usually I use "songroger" as my ID everywhere.
  I was born and raised in Hunan China.
  I'm really fond of beautiful design, drawing etc.

# Contact and social media links
# twitter_username: songrogero
github_username: KKLater
# facebook_username: song.roger.1
# instagram_username: songroger198
# linkedin_username: songroger

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM
highlighter: rouge
# If U enable the comment, edit disqus or duoshuo account
# before deploy your webpage
enable_comment: false
# disqus_account: songroger

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
