# Basic
title: WngLMng's Blog
author: WngLMng
description: 嗨，我是王立明，一名来自黑龙江省鹤岗市的男生。<br/>现于无线生活（北京），从事互联网开发工作。

url: "http://www.lshxin.com"

permalink: /:year/:month/:title/

# Format
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]
  
# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    weibo: sunmoon1993
    github: wnglmng
    gplus: 112547382138552250597
    mail: wnglmng@gmail.com
